### ISSUE TITLE
User.BirthDate is int64 instead of string

### ISSUE THREAD

**Issue by JonasDoe** [FusionAuth/go-client#13]
In the client the `User`'s `BirthDate` field is declared as `int64` (see [here](https://github.com/FusionAuth/go-client/blob/master/pkg/fusionauth/Domain.go#L2682)), while the documentation demands a `string` (of format `yyyy-MM-dd` in Java terms) (see [here](https://fusionauth.io/docs/v1/tech/apis/users#create-a-user)). Therefore, any requests aiming to create or modify a user and setting the `BirthDate` on the way will fail. So, if I use the Go client to send a request to the API specifiying the birthdate, it will lead to an error message telling me the BirthDate could not be parsed at index 0.
I would fix that myself and create a pull request, but since the clients are generated that wouldn't help much, would it?

**Comment by robotdan** [comment]
Thanks for letting us know @JonasDoe . 

In Java that field is a `java.time.LocalDate`, and we serialize it to `yyyy-MM-dd`. So in the Go client, we could either just use a String or provide some custom serialization / de-serialization. 

You may have already figured out how all of this comes together, but if not. 

JSON definition of the FusionAuth User object, this gets built from our Java domain.
https://github.com/FusionAuth/fusionauth-client-builder/blob/master/src/main/domain/io.fusionauth.domain.User.json

Here is the macro file that maps the Java types into language specific values:
https://github.com/FusionAuth/fusionauth-client-builder/blob/master/src/main/client/_macros.ftl

And the Go Domain template which uses the macro file above. 
https://github.com/FusionAuth/fusionauth-client-builder/blob/master/src/main/client/go.domain.ftl

@matthew-altman It looks like `LocalDate` and `ZonedDateTime` are being set as `int64` in Go. For the `LocalDate` - at least for the `birthDate` in the User object we'll need to serialize this to a `yyy-MM-dd` String. We can either just switch this to a string, or add some serialization and de-serialization code. 

Can you take a look and see if there are other uses of `LocaleDate` that may also have this issue, I think this is the only one on the API, but let's double check.

**Comment by matthew-altman** [comment]
The only LocalDate in the domain is the User BirthDate field. Some of our other clients, such as CSharp and JS, covert LocalDate to a String. So for consistency we should probably just do the same for Go.
