### ISSUE TITLE
how to fetch the refresh token

### ISSUE THREAD

**Issue by alonlong** [FusionAuth/go-client#14]
Hi, I am trying to fetch the init refresh token by the login api, but the refresh token in response is empty. Why?

code:
var credentials fusionauth.LoginRequest
credentials.LoginId = "xxxxxxxxx"
credentials.Password = "xxxxxx"

// Use FusionAuth Go client to login the user
response, _, err := auth.Login(credentials)
if err != nil {
   panic(err)
}

response:
{
    "statusCode":200,
    "token":"xxxxxxxxxxxxxxxxxxxxxxx",
    "user":{
        "id":"04f1179f-f21e-4ab1-b5e1-0b565e8aedd4",
        "passwordLastUpdateInstant":1577921277919,
        "verified":true,
        "active":true,
        "email":"xxxxxxxx",
        "insertInstant":1577921277858,
        "lastLoginInstant":1579134696920,
        "registrations":[
            {
                "applicationId":"3c219e58-ed0e-4b18-ad48-f4f92793ae32",
                "id":"5a36c8ed-20e4-4390-9f4d-5dd017cbda0f",
                "insertInstant":1577924008508,
                "roles":[
                    "api_key_manager",
                    "application_deleter",
                    "application_manager",
                    "audit_log_viewer",
                    "lambda_manager",
                    "report_viewer",
                    "webhook_manager"
                ],
                "usernameStatus":"ACTIVE",
                "verified":true
            },
            {
                "applicationId":"8af9b71b-5637-435c-9f4c-fb82e17dd114",
                "id":"2a863715-4de2-4932-81a4-a37b298e4187",
                "insertInstant":1577921854040,
                "lastLoginInstant":1578960128426,
                "username":"alon",
                "usernameStatus":"ACTIVE",
                "verified":true
            }
        ],
        "tenantId":"e0dede59-09ab-701b-e6da-8c7911ff6464",
        "twoFactorDelivery":"None",
        "username":"alon",
        "usernameStatus":"ACTIVE"
    }
}

**Comment by robotdan** [comment]
By default refresh tokens are not generated by the Login API. You can enable the refresh token in the Application security settings. 

`Applications > Edit > Security Tab > Generate refresh tokens`
`Applications > Edit > Security Tab > Allow token refresh`

https://fusionauth.io/docs/v1/tech/users/applications#security

**Comment by alonlong** [comment]
OK, I'll try it, TKS

**Comment by alonlong** [comment]
@robotdan  By default refresh tokens are not generated by the Login API. So how can i get the fresh token and keep freshing the token with client?

**Comment by robotdan** [comment]
You'll need to provide an `applicationId` on the Login request if you want to receive a refresh token. 

https://fusionauth.io/docs/v1/tech/apis/login#authenticate-a-user

```
var credentials fusionauth.LoginRequest
credentials.LoginId = "xxxxxxxxx"
credentials.Password = "xxxxxx"
credentials.ApplicationId = "8af9b71b-5637-435c-9f4c-fb82e17dd114"
```

**Comment by alonlong** [comment]
@robotdan it's ok now~ thank you very much

**Comment by alonlong** [comment]
@robotdan Hi, I fetch the access token and refresh token by the login api. I can use the refresh token to exchange the access token, but the refresh token must have the expire time, how can i update the refresh token?
