### ISSUE TITLE
does refresh token has expire time?

### ISSUE THREAD

**Issue by alonlong** [FusionAuth/go-client#15]
Hi, I fetch the access token and refresh token by the login api. I can use the refresh token to exchange the access token, but the refresh token must have the expire time, how can i update the refresh token?
I think the fusion api 'ExchangeRefreshTokenForJWT' which is used to exchange the access token by refresh token can return a new refresh token, but the slice in response is empty.
Or if the refresh token is expire, the user should login again?

**Comment by robotdan** [comment]
Yes, a refresh token has a configured TTL. It can be configured at the Tenant or Application level. 
https://fusionauth.io/docs/v1/tech/core-concepts/tenants#jwt
