### ISSUE TITLE
ExchangeRefreshTokenForJWT does not work with APIKey

### ISSUE THREAD

**Issue by oottinger** [FusionAuth/go-client#17]
I currently have my fusion auth client setup to use an APIKey.  When calling the refresh token method as so

```
refreshResponse, errorList, err := fusionAuthClient.ExchangeRefreshTokenForJWT(fusionauth.RefreshRequest{
	RefreshToken: refreshToken,
})
```

`errorList` will contain an error stating I have not set the TenantID in the header.  This is because the underlying method is calling `StartAnonymous(...)` instead of `Start(...)`.  The current work around for me is to grab the configured tenant id and call the `SetTenantId` method.

My expectation was for the method to work with the APIKey since I have it set on my fusionauth rest client.

**Comment by matthew-altman** [comment]
@oottinger The `ExchangeRefreshTokenForJWT` endpoint does not require authentication, so in this case the `StartAnonymous` is correct. However, it does look like you stumbled across a bug in a multi-tenant environment. Using the `SetTenantId` is a valid workaround at the moment. We already have a fix, which is in the FusionAuth codebase, and not the client, and will be resolved in version 1.14.1
https://github.com/FusionAuth/fusionauth-issues/issues/454
