### ISSUE TITLE
Complete example

### ISSUE THREAD

**Issue by henri9813** [FusionAuth/go-client#18]
Hello, 

Is it possible to have a full example of a little app with 2 routes to have an example of how use your library ?

Thank you very much,

Best regards

**Comment by Gowiem** [comment]
@henri9813 As part of writing a blog post for FusionAuth, I've made the following FA golang-client example here: [masterpointio/fusionauth-golang-client-example](https://github.com/masterpointio/fusionauth-golang-client-example). That might help you along!

**Comment by henri9813** [comment]
Oh thank you very much !

I didn't know that we can retrieve JWT from oauth !  ( i don't find anything about this in the documentation :( ) 


Best regards.

**Comment by mooreds** [comment]
@Gowiem 's example has been moved to https://github.com/FusionAuth/fusionauth-example-go-device-code-grant/

@henri9813 can we close this issue or do you consider it still open?

**Comment by henri9813** [comment]
Hello @mooreds ,

I will post a project example for a FusionAuth Middleware for Gorilla mux.

That's 'important' thing when we deal with Micro-Service today.

**Comment by mooreds** [comment]
That'd be great! 

I'd suggest posting it in the forums: https://fusionauth.io/community/forum/categories

In the 'blogs' if there's a corresponding blog post, otherwise in 'general discussion'.
