### ISSUE TITLE
Two LambdaConfiguration structs?

### ISSUE THREAD

**Issue by pericson004** [FusionAuth/go-client#23]
Getting compile error because two structs have the same name in commit "rebuild domain after removing omitempty from bool types. Fix for #22", master branch, committed yesterday 
1 parent b6a7bd6 commit 25495fef79c3b2c837faf487e7b51ef2bbfe6599

Error is:
 github.com/FusionAuth/go-client/pkg/fusionauth
../../../../pkg/mod/github.com/!fusion!auth/go-client@v0.0.0-20200619185324-25495fef79c3/pkg/fusionauth/Domain.go:1754:6: LambdaConfiguration redeclared in this block
        previous declaration at ../../../../pkg/mod/github.com/!fusion!auth/go-client@v0.0.0-20200619185324-25495fef79c3/pkg/fusionauth/Domain.go:1748:6
```
type LambdaConfiguration struct {
  AccessTokenPopulateId     string                    `json:"accessTokenPopulateId,omitempty"`
  IdTokenPopulateId         string                    `json:"idTokenPopulateId,omitempty"`
  Samlv2PopulateId          string                    `json:"samlv2PopulateId,omitempty"`
}

type LambdaConfiguration struct {
  ReconcileId               string                    `json:"reconcileId,omitempty"`
}
```

My guess is this is a merge issue and the LambdaConfiguration struct should look like this:
```
type LambdaConfiguration struct {
  AccessTokenPopulateId     string                    `json:"accessTokenPopulateId,omitempty"`
  IdTokenPopulateId         string                    `json:"idTokenPopulateId,omitempty"`
  ReconcileId               string                    `json:"reconcileId,omitempty"`
  Samlv2PopulateId          string                    `json:"samlv2PopulateId,omitempty"`
}
```

**Comment by robotdan** [comment]
I think this commit should resolve this for you. 
https://github.com/FusionAuth/go-client/commit/48758725366958cf4b3765eba28e981190b90a2d
