### ISSUE TITLE
Incorrect Event Types

### ISSUE THREAD

**Issue by autom8ter** [FusionAuth/go-client#28]
Incorrect Event Type strings https://godoc.org/github.com/FusionAuth/fusionauth-go-client/pkg/fusionauth#EventType. They should be `user.update`, `user.delete`, `user.create`, etc as seen in the API docs here: https://fusionauth.io/docs/v1/tech/apis/webhooks#create-a-webhook.

**Comment by robotdan** [comment]
Thanks for reporting @autom8ter !
