### ISSUE TITLE
bug in string conversion of id for RetrieveEventLog and RetrieveAuditLog

### ISSUE THREAD

**Issue by code-sleuth** [FusionAuth/go-client#35]
There's an error in conversion of integer value to string when retrieving an event log and an audit log.

Error from fusionAuth
```
{"fieldErrors":{"id":[{"code":"[couldNotConvert]id","message":"java.lang.NumberFormatException: For input string: \"\u0001\""}]},"generalErrors":[{"code":"[invalid]","message":"Your GET request is missing the Id on the URL."}]}
```

Conversion Issue Reproduced: https://play.golang.org/p/_AqXx9yf5VF

Go Version:
`go version go1.13.4 darwin/amd64`

**Comment by robotdan** [comment]
I fixed in the client builder. Should be fixed via https://github.com/FusionAuth/fusionauth-client-builder/commit/38ba0e3748980c51d4f45cbe63104b8085a00dc5
