### ISSUE TITLE
[Question] Use the client with only API KEY

### ISSUE THREAD

**Issue by Tintwo** [FusionAuth/go-client#47]
In some case (eg. automation), we don't need to log in with a specific user but use directly an "admin api key".

Is there a way to use client method without pre-auth of a user, like we can do directly with an api key and and REST client ? If so, I didn't found any documentation for this.

Regards.

**Comment by mooreds** [comment]
It sounds like you are trying to call a method on the API with only an API key? Is that correct?

If so, which method of the API are you trying to call?

**Comment by Tintwo** [comment]
It's correct.
Basically, all routes to create/manage tenant, application, users, groups & roles.

**Comment by mooreds** [comment]
Ah, ok. You should be able to use any of the API methods with just the API key. See the example I just added to the readme: https://github.com/FusionAuth/go-client/commit/981e140abcb02dff37b4dda49d30d31aef3c25ed

Also, just a heads up that opening an issue to ask a question isn't the best way to get it answered. The best way in the future is to open up a forum post: https://fusionauth.io/community/forum/

I'll change the README to indicate that.

**Comment by mooreds** [comment]
I'm going to close this out, @Tintwo , but please feel free to post any further questions in the forum.
