### ISSUE TITLE
Invalid Content-Type when making requests against server

### ISSUE THREAD

**Issue by oottinger** [FusionAuth/go-client#68]
I had just recently upgraded to 1.39.0 from 1.38.1.  When I try to call this method on the client:

```
func (c *FusionAuthClient) RetrieveApplication(applicationId string) (*ApplicationResponse, error) {
	var resp ApplicationResponse

	err := c.Start(&resp, nil).
		WithUri("/api/application").
		WithUriSegment(applicationId).
		WithMethod(http.MethodGet).
		Do()
	return &resp, err
}
```

I am getting the following error: `Invalid [Content-Type] HTTP request header value of [text/plain]. Supported values for this request include [application/json].`

I believe the issue is this line:
https://github.com/FusionAuth/go-client/blob/master/pkg/fusionauth/Client.go#L91

When I change the code to utilize `application/json` for the `Content-Type`, my integration tests work.  This likely impacts all API calls, but I did not test to validate this.

These calls used to work on 1.38.1.

**Comment by mooreds** [comment]
Thank you @oottinger . I know we have made some changes to how we handled the content-type (see https://fusionauth.io/docs/v1/tech/release-notes#version-1-39-0 ) but I'm not sure if the issue is in the client or our server.

**Comment by mooreds** [comment]
Will be tracking this here https://github.com/FusionAuth/fusionauth-issues/issues/1876

Thanks again for reporting this, @oottinger

**Comment by robotdan** [comment]
Pushed https://github.com/FusionAuth/go-client/commit/2f91b2374ac5020ff504c97885160b6126a8d8a8 can you retry?

**Comment by oottinger** [comment]
It works now, thanks!
