### ISSUE TITLE
WebhookIDs not available on tenant

### ISSUE THREAD

**Issue by sjauld** [FusionAuth/go-client#70]
WebhookIDs were added to the tenant in 1.37.0, but they're not in the SDK.

**Comment by mooreds** [comment]
Thanks for reporting @sjauld ! We'll track against https://github.com/FusionAuth/fusionauth-issues/issues/1984

**Comment by mooreds** [comment]
Heya, @sjauld we look a look at this and you need to put the webhook id on the tenant request. More details in the linked bug, but I'm going to close this out.

If you can provide repro steps for the issue, please let us know and we'll re-open.
