### ISSUE TITLE
Unable to consume go-client v0.0.0-20240624180314-2e401feb55f7

### ISSUE THREAD

**Issue by jakobfaerch** [FusionAuth/go-client#82]
When I change my go.mod from referencing 
`github.com/FusionAuth/go-client v0.0.0-20240613012702-a3bace236e64`
to use
`github.com/FusionAuth/go-client v0.0.0-20240624180314-2e401feb55f7`

I end up with an error from the go compiler stating
```
 external/com_github_fusionauth_go_client/pkg/fusionauth/Domain.go:4010:2: undefined: LinkedHashMap
 ```

It seems like 2e401feb55f704fb3150723a1548dc24b3219d6d could be the cause, it introduces the sole use of `LinkedHashMap` in `Domain.go`. @robotdan authored that. 

I see release version commits in the commit history. Could this simply be an error in the way I consume the library?

**Comment by TMeireOqton** [comment]
We're seeing the same thing in our project. It seems like the client builder set a dependency on LinkedHashMap in the StatusResponse, without actually generating that type in the repository.

**Comment by robotdan** [comment]
Thanks for reporting @jakobfaerch and @TMeireOqton. Looking ...

**Comment by robotdan** [comment]
@mooreds Not that I am aware. Here is how we are handling it for .NET. 

- https://github.com/FusionAuth/fusionauth-netcore-client/blob/361c1acecce4949e5ccf3ca1472fa9a2bda928ac/fusionauth-netcore-client/domain/io/fusionauth/domain/api/StatusResponse.cs#L29
- https://github.com/FusionAuth/fusionauth-client-builder/blob/0b7dfe6aa89784f4eb7852bf106377b8aa20de7a/src/main/client/_macros.ftl#L27
